# Generated by Django 2.1.dev20171010132034 on 2017-10-13 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antropometria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('bisep', models.FloatField()),
                ('trisep', models.FloatField()),
                ('cuadrisep', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_banco', models.CharField(max_length=200)),
                ('nro_cheque', models.IntegerField()),
                ('fecha_chque', models.DateField()),
                ('monto_cheque', models.IntegerField()),
                ('estado_cheque', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('fec_nac', models.DateField()),
                ('genero', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_test', models.CharField(max_length=200)),
                ('precio_test', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestParametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('genero', models.CharField(max_length=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Test')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Test'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='test_parametro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.TestParametros'),
        ),
        migrations.AddField(
            model_name='antropometria',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cliente'),
        ),
    ]
